### ISSUE TITLE
"...edit a markdown document it should instantly preview in your browser" -- it does not

### ISSUE THREAD

**Issue by leegee** [dbankier/vscode-instant-markdown#1] opened 2016-03-16 10:34 UTC
"When you edit a markdown document it should instantly preview in your browser with changes applied as you type."
Doesn't open a browser, doesn't seem to do anything at all.
What can I tell you?

VSC v0.10.11
Date 2016-03-11
Shell 0.35.0
Renderer 45.0.2454.85
Node 4.1.1

Default browser: latest Chrome

OS: fully patched Windows 10.

**Comment by teok** [comment] 2016-04-05 14:48
Same issue for me. I have Windows 10 and I tried with Chrome Firefox and Edge as default browser.

**Comment by jkvim** [comment] 2016-04-21 04:46
@leegee check has the plugin installed success and try open http://localhost:8090 in browser and click the markdown file you want to edit. then it will render on the browser. this work for me.

**Comment by leegee** [comment] 2016-04-21 07:01
Installed just now with the latest 'insiders' version of VSCode and the latest stable release, opened an .md file, edited, saved, opened in http://localhost:8090 in Chrome, but 'localhost refused connection'

**Comment by jamietre** [comment] 2016-05-26 16:27
`instant-markdown-d` doesn't work in windows, confirmed it a second ago. There's an old pull request to fix, I just requested it be merged. Presumably that would fix the problem with instant-markdown. 

https://github.com/suan/instant-markdown-d/pull/15

**Comment by btbxbob** [comment] 2016-11-09 06:19
Not working here, too. windows 7. i think it's the problem @jamietre said.

**Comment by leegee** [comment] 2016-11-09 08:43
FWIW now works on OSX

**Comment by aarmand** [comment] 2016-11-24 16:10
El Capitan
VSCode Version 1.7.2 (1.7.2)

Not working on osx for me.
![screen shot 2016-11-24 at 17 08 20](https://cloud.githubusercontent.com/assets/2370391/20604848/cfd938e8-b268-11e6-8b85-4573fe5ab470.png)

**Comment by aarmand** [comment] 2016-11-24 16:33
Figured it out in my case. If you have https://github.com/hnw/vscode-auto-open-markdown-preview installed in vs code, even if its disabled, this project wont render in the browser. Seems to be some kind of conflict. I uninstalled and browser render worked. Hope that helps.

**Closed** 2016-11-27 23:29 UTC

**Comment by junfkt2** [comment] 2016-11-30 16:37
it could auto open browser and show the result earlier today, but now it could not 
, i have to open the browser manually and input the address "http://localhost:8090",

who can tell me why? thank you very much.

**Comment by dbankier** [comment] 2016-11-30 20:58
@junfkt2 , which os?

**Comment by junfkt2** [comment] 2016-12-01 07:46
Thank you,

my os is Windows 10(14393),64 bit

[cid:image001.png@01D24BEA.0F94DBD0]

发件人: David Bankier [mailto:notifications@github.com]
发送时间: 2016年12月1日 4:58
收件人: dbankier/vscode-instant-markdown <vscode-instant-markdown@noreply.github.com>
抄送: junfkt2 <registerr6w4@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [dbankier/vscode-instant-markdown] "...edit a markdown document it should instantly preview in your browser" -- it does not (#1)


@junfkt2<https://github.com/junfkt2> , which os?

**Comment by JamesEarle** [comment] 2017-03-13 20:50
I am having an issue where it will open Edge every time I open a `.md` file, even if the file is already open in the editor elsewhere, but Edge never renders even simple markdown and then crashes when trying to get to http://localhost:8090
